### ISSUE TITLE
Add aborter callback to forEach()

### ISSUE THREAD

**Issue by poelstra** [poelstra/ts-stream#14]
See proposals and background in #6.

**Comment by poelstra** [comment]
Implemented in 0.5.1.

**Comment by rogierschouten** [comment]
Having this feature means that it could have a function to have the abort() method on the Writable interface again, I think?  To cause this call to happen, so that pending writes are aborted by the individual streams?

**Comment by poelstra** [comment]
Yup, added to the Common interface now.
