### ISSUE TITLE
toArray()

### ISSUE THREAD

**Issue by rogierschouten** [poelstra/ts-stream#19]
It may be handy to add a toArray() function to a ReadableStream, just like you have a from() function to get a stream from an array.

I've currently implemented this:
```javascript
export function toArray<T>(stream: Readable<T>): Promise<T[]> {
	var result: T[] = [];
	stream.forEach((value: T): void => {
		result.push(value);
	});
	return stream.result()
		.then((): T[] => result);
}
```

**Comment by poelstra** [comment]
Yeah, I've implemented something similar myself too, but didn't get around to add it yet due to missing unit tests :)

Thanks!

**Comment by rikkertkoppes** [comment]
Maybe a reduce would be more versatile?

**Comment by poelstra** [comment]
We probably need both: toArray() to simply read everything in the stream, and reduce() as counterpart to map() and filter().

It's on pause though while I'm on holiday ;)

**Comment by rikkertkoppes** [comment]
Hacked together a reduce() like this (i know, js...)

    var Stream = require("ts-stream").Stream;
    var Promise = require("bluebird");

    Stream.prototype.reduce = function(cb, initial) {
        return this.forEach(function(value) {
            initial = cb(initial,value);
        }).then(function() {
            return initial;
        });
    }

    Stream.from([4,1,2,1])
        .map(function(n) {
            return Promise.resolve(n * 2).delay(n * 1000);
        })
        .reduce(function(all,n) {
            return all.concat(n);
        },[]).then(function(res) {
            console.log(res);
        });

This brings stuff more inline with from() I guess, since it allows you to collapse the stream back into a single value (array in this case)

This is a valuable tool when you create streams of streams. When you first map() to streams of streams, it allows you bring the results of those back again to a single value. Like so:

    var Stream = require("ts-stream").Stream;
    var Promise = require("bluebird");

    function range(n) {
        return Array.apply(null, Array(n)).map(function (_, i) {
            return i;
        });
    }

    Stream.prototype.reduce = function(cb, initial) {
        return this.forEach(function(value) {
            initial = cb(initial,value);
        }).then(function() {
            return initial;
        });
    }

    Stream.from([4,1,2,1])
        .map(function(n) {
            return Stream.from(range(n))
                .map(function(m) {
                    return Promise.resolve(m).delay(n * 1000);
                })
                .reduce(function(sum, n) {
                    return sum + n;
                },0);
        })
        .reduce(function(all,n) {
            return all.concat(n);
        },[]).then(function(res) {
            console.log(res);
        });
