### ISSUE TITLE
resolve the end() promise of an aborted stream with no readers automatically

### ISSUE THREAD

**Issue by rogierschouten** [poelstra/ts-stream#20]
I just experienced a situation where I was still putting together a stream when I got an error. I nicely aborted the stream source, and waited for source.result() to end the whole process.  To me, the source is important to end because it has an in-use database connection associated with it that needs to be freed.
However, as the whole stream was not yet connected, this process never ended (since abort() resulted in an end() and nobody answered the end()). 
I'm not sure what the best solution would be here. Does this warrant another corner case where an aborted stream with no readers will resolve its end() calls, just like it has already rejected its write calls ?

**Comment by rogierschouten** [comment]
In any case, for these scenarios it would be very handy to be able to detect whether a stream has any readers. If not, the error handler could attach a dummy reader to end the stream.

**Comment by rikkertkoppes** [comment]
Not sure whether this is the same problem, but had a stream like this:

    somePromise.then(function() {
        return Stream.from(input)
            .map(mapper)
            .forEach(log,handleEnd,handleAbort);
    })

When an error is thrown in the mapper, the stream aborts and handleAbort is called as expected (after figuring out there was a third parameter)

However, the returned promise (from result()) does not resolve nor reject. I expected it to reject.

The abort handler does not do a whole lot, only logging, should I do something explicit there to reject the result()?

**Comment by rogierschouten** [comment]
@rikkertkoppes   That is caused by #16 , it's a bug.

**Comment by poelstra** [comment]
@rogierschouten I don't really like the idea of automagically ending the stream in such cases. Especially considering that people may still decide to attach `forEach()` later, so the library cannot make that decision, I think.

Having a simple getter to see whether forEach() has been called on the stream already is a good idea though. Will add this.

@rikkertkoppes That's indeed unrelated to this issue (and is solved in 0.6.1). You should not need an abort handler in most cases (unless your `log` or `handleEnd` callbacks may be lengthy, in which case this allows to abort them).

**Comment by rogierschouten** [comment]
I agree.
