### ISSUE TITLE
Multiple writes and error handling

### ISSUE THREAD

**Issue by rogierschouten** [poelstra/ts-stream#22]
As per your example code, the database drivers we have send 10-20 writes into a querystream at once. However, if a write() fails, the already-sent subsequent writes are still passed along the stream.

Would it be an idea to reject all queued writes when the current one is rejected? It was my intuition that it would, and it would save some state management.

**Comment by poelstra** [comment]
Interesting question. The idea is that individual writes are allowed to fail, but I can see your point.

I remember we had similar discussions a while back on how to handle the case when a bunch of write()'s and an end() has been 'queued', and a stream is then abort()'ed, and whether to then also cancel those writes (which we decided to do) and the end (which we decided not to do).

Maybe it could be a setting/mode/whatever on the stream what to do with such queued writes. It could maybe also (optionally) automatically call abort() (but not end()) on a stream when this happens.

**Comment by rogierschouten** [comment]
Calling abort() with the write error would be an implementation of rejecting subsequent writes. I don't think a mode setting would be useful, as you would have to ensure that all parts of a stream have the same mode then. Assuming that some sources and sinks are third-party, it will be hard to ensure.

**Comment by poelstra** [comment]
> as you would have to ensure that all parts of a stream have the same mode then

Why? Any pending writes are only buffered by the 'first' stream, they are not sent along until each of them is 'acknowledged'. So the first stream element that has this behavior can decide the fate of any further writes. It's even possible (and quite trivial) to implement this as a transform() today, I think.

So maybe we don't even need a mode, just an abort-on-error transform that you can apply?

**Comment by rogierschouten** [comment]
... after discussion: StreamSource subclass with buffering, low/high watermark, low/high signals. The StreamSource should (possibly optionally) reject subsequent writes after an error.

**Comment by poelstra** [comment]
Considering this item fixed, given previous comment.
