### ISSUE TITLE
let from() take a promise

### ISSUE THREAD

**Issue by rikkertkoppes** [poelstra/ts-stream#23]
If an array I want to put into a stream is the result of an asynchronous operation, it would be beneficial to be able to do 

    Stream.from(Promise.resolve([1,2,3,4]));

to create the stream. One way to implement it is:

    Stream.from = function (data) {
        // TODO: consider rewriting to use .forEach()
        var stream = new Stream();
        var i = 0;
        var aborter = function (error) {
            if (error) {
                // TODO
                // - Explode?
                // - maybe only have `static into<T>(writable, data): Promise<void>`?
                // - allow passing an end-callback?
                // - expect people to listen for result()?
                stream.abort(error);
            }
        };
        Promise.resolve(data).then(function(data) {
            var loop = function () {
                if (i >= data.length) {
                    return stream.end().done(undefined, aborter);
                }
                stream.write(data[i++]).done(loop, aborter);
            };
            loop();
        });
        return stream;

**Comment by poelstra** [comment]
Implemented in 0.6.1.
