### ISSUE TITLE
Let result() be rejected when end() is called with an error argument

### ISSUE THREAD

**Issue by poelstra** [poelstra/ts-stream#25]
While rewriting `writeEach()` (well, while writing the tests for it), it became clear that it's more useful to have a stream's `result()` be rejected when `end()` is called with an error (instead of just looking at the result of the end-callback, as we currently do).

This can already be 'emulated' by e.g. doing: `end(myError, Promise.reject(myError))` (in fact, this is what I've done in `writeEach()` for now), but I think it makes sense to make that the default behavior for `end()`.

However, there's the question about how to handle e.g. the corner-case of both ending with an error, and then the end-callback also returning a (different) error. Should `result()` then be end-callback's error (current case), or `end()`'s error argument? Or maybe these errors both be 'combined' into some aggregate error object.

Hopefully, this would also simplify/obsolete the `composeEnders()` function in Transform.ts...

**Comment by rogierschouten** [comment]
Can you explain why it's more useful? The current implementation has the advantage that the error can be replaced by the sink's end handler. For instance, one could turn an abort error into no error (I don't currently do this). What is the advantage of the other implementation?

**Comment by poelstra** [comment]
It's true that it may be nice to be able to 'swallow' an abort error this way, but I'm wondering whether that's the common case.

For example, the default ender of forEach now 'bounces' the error back, in order to make the stream's result POLA by default (i.e. ending a stream with an error leads to the stream's `result()` being that error).

Consider this example though:
```ts
stream.forEach(dataHandler, (error) => { console.log("stream done", error); });
stream.end(new Error("boom"));
```

In this case, the end callback simply returns void (which I think is a very common case), which now leads to this stream's `result()` to be 'no error', whereas removing the end handler DOES lead to `result()` being the 'boom' error.

Again, I'm not completely sure what the behavior should be exactly, but the current behavior is likely going to surprise users. I'll definitely keep the 'swallow abort' use case in mind when I'm going to experiment with this.

**Comment by rogierschouten** [comment]
I agree that it looks a bit weird syntactically. But it's not that severe:

Using this promise library requires the user to learn anyway that writes go to the sink, come back to the source, ends go to the sink, come back to the source, and then result() is fulfilled. Knowing that, it is not a difficult concept that swallowing an error in the end() handler (just like you would in a Promise.catch() handler) would cause the error not to propagate.

**Comment by poelstra** [comment]
Good example to compare it with `catch()`.
I suppose I mentally compare it more with `finally()`, though :)
