### ISSUE TITLE
Relay method

### ISSUE THREAD

**Issue by rikkertkoppes** [poelstra/ts-stream#26]
For my implementation I am using a relay method, which is basically

    Stream.prototype.relay = function(to) {
        this.forEach(function(value) {
            return to.write(value);
        });
    }

My usecase is a set of nodes that have input and output stream(s) defined. When connecting two nodes, I use this.

It may be a basic addition.

**Comment by poelstra** [comment]
You mean something like `.pipe()`? :)

```ts
	/**
	 * Read all values and end-of-stream from this stream, writing them to
	 * `writable`.
	 *
	 * @param  writable Destination stream
	 * @return The stream passed in, for easy chaining
	 */
	pipe<R extends Writable<T>>(writable: R): R;
```

**Comment by rikkertkoppes** [comment]
Ah, missed it in the docs and completely forgot the canonical name.

Nm.
