### ISSUE TITLE
Conflicting node typings version

### ISSUE THREAD

**Issue by mgroenhoff** [poelstra/ts-stream#28]
In your package.json you have a dependency on a specific version of @types/node (v6) which results in Conflicting definitions for 'node' if I depend on v7.

My suggestion is to change the semver pattern to "latest" or "*"

**Comment by poelstra** [comment]
Thanks a lot @mgroenhoff !
Nice touch of even updating the Changelog :+1: 

Released in 0.9.1 on npm.
