### ISSUE TITLE
Proposal: Divorce forEach from Stream interface

### ISSUE THREAD

**Issue by martinheidegger** [poelstra/ts-stream#37]
I have been working a lot with light-weight streams that basically just implement the "forEach" method and skip on all the rest. I really enjoy this approach and it feels very light-weight an efficient.

That being said, it kind-of bothers me that forEach can be called "only-once":
You create a stream: the stream object should be already returned.

It dawned to me that there is the possibility to go even more light-weight in ts-stream@3 with a change in API.

```typescript
/**
 * IStreamOptions contains all the options required for a stream.
 * I noticed that validating the properties can be really hard to get
 * right, if all are put in one object: the object can be verified and
 * processed in the same way across different "Stream" implementations
 */
interface IStreamOptions<T> {
  reader (item: T): PromiseLike<void> | void
  ender?: (error?: Error) => void,
  aborter?: (error: Error) => void
}

/**
 * This is basically Readable without the "forEach" method. This way there
 * is no chance that forEach is executed twice.
 */
interface IStreamState {
  aborted (): PromiseLike<never>
  result (): PromiseLike<void>
  abort (reason: Error): void
}
```

How would we create a stream with this API?

```typescript
import { prepareOptions } from 'ts-stream'

function createMyStream<T> (options: IStreamOptions): IStreamState {
  // Attaches ender & aborter to the stream
  const state = new StreamState<T>(options)
  // Makes sure that the data is pushed (with backpressure)
  state.push(data)
  state.aborted().catch((err) => {
    // If the system needs to take care of aborts
  })
  // The class has a "end" operation to end the state
  setTimeout(() => state.end(), 200)
  return state
}
```

**Comment by poelstra** [comment]
This is trivial to implement in the current API already:

```ts
import Stream, { WritableStream } from "ts-stream";

interface Reader<T> {
    reader: (value: T) => void | PromiseLike<void>;
    ender?: (error?: Error) => void | PromiseLike<void>;
    aborter?: (error: Error) => void;
}

function createMyStream<T>(reader: Reader<T>): WritableStream<T> {
    const stream = new Stream<T>();
    stream.forEach(reader.reader, reader.ender, reader.aborter);
    return stream;
}
```

Example usage:

```
const w = createMyStream<number>({
    reader: (v) => console.log(v)
});

await w.write(1);
await w.end();
```

The only tricky thing here is that the promise returned from `forEach()` becomes 'dangling'. So if no-one else catches exceptions from it, it will cause an unhandled rejection.

**Comment by poelstra** [comment]
Sure, but the cost of instantiation of a big or a small class is the same (it's just assignment of the prototype). The most interesting part (i.e. the `_pump()`) is necessary in any case.

The only other downside I see is that the 'protection' only works in TS. In plain JS, you still have access to methods like `.forEach()` (but they will of course give you a nice error). This is not specific to `ts-stream` though. It's very often possible to get to all kinds of internals in JS classes if you want to.

I did experiment (long time ago) with patterns like this, but in the end didn't really get to a set of interfaces I liked better than what `ts-stream` currently provides.
Note that you'd also have to create counterparts for the 'reverse' scenario (i.e. a `createMyReadable(writer: Writer)`-style interface), and some way to 'couple' (pipe) them.

**Comment by martinheidegger** [comment]
I have been experimenting with an extracted State:

https://github.com/pnext/pnext-io/blob/5de4f68166bb42d4d7a51125c2bc520f0d7ca658/ts/reader/feed/StreamState.ts

I am happy that the code can be so reduced _(i am sure this was an initial goal of you)_ but reading through the code I really think that forEach belongs in the constructor:

https://github.com/pnext/pnext-io/blob/5de4f68166bb42d4d7a51125c2bc520f0d7ca658/ts/reader/feed/StreamState.ts#L59-L78

**Comment by poelstra** [comment]
Minimizing amount of (library-)code was not an explicit goal.

Note that a lot of the 'code' of ts-stream is actually comments and interfaces. The actual minified JS is not that large (the core functionality seems roughly comparable to your lazyPromise + StreamState?). Plus, it supports backpressure when writing (e.g. writeEach()).

As far as I understood, your implementation doesn't care about backpressure (which may be fine for your purpose, if you accept the fact that your 'push queue' may now become infinitely large if your writer is faster than your reader). If so, it seems you have a different goal, and you could of course just use whatever you like.

Also, as stated before, your suggestion only deals with one 'direction' (i.e. creating 'sinks', by passing `forEach()` args to the constructor). If you need the opposite case (i.e. creating sources, by passing `writeEach()` args) you'd need a different implementation. With my current API you can easily have both worlds (as shown in my example, above).

**Comment by martinheidegger** [comment]
Yes, ts-stream is small as it is. I wrote this implementation in part as an exercise to understand the difficulty of your implementation, but also saw it as an attempt to see if there is space for improvement. I am working often on/with protocol level code and I am wondering if going for faster, leaner, better API might be the goal to make it popular. Reaching (and exceeding) the performance (and size) of the streams API with support for promises.

As I understand, backpressure is supported if the the promise returned by reader prevents further reading of data.

* [Every operation on the state can return a promise, if it does the StreamState waits until proceeding with next](https://github.com/pnext/pnext-io/blob/5de4f68166bb42d4d7a51125c2bc520f0d7ca658/ts/reader/feed/StreamState.ts#L112)

* [A Stream implementation adds the `.next` operation, which is placed after the read in the stack](https://github.com/pnext/pnext-io/blob/5de4f68166bb42d4d7a51125c2bc520f0d7ca658/ts/reader/feed/createReadStream.ts#L115)

Please correct me if I am wrong, but this should be a valid implementation of backpressure?

**Comment by poelstra** [comment]
> Please correct me if I am wrong, but this should be a valid implementation of backpressure?

No, your `push()` and `end()` don't return a promise, which can cause a fast sender to e.g. overflow available memory.

I'm closing this issue, as I don't see a compelling reason for creating a completely different implementation (in this package).
