### ISSUE TITLE
What about reading from 

### ISSUE THREAD

**Issue by MarcWeber** [poelstra/ts-stream#40]
I have the case 1) read chunks 2) turn into csv rows 3) jam 50 items 4) write 50 items to database.
It would be nice if you could document why you didn't add such file reader because createReadStream.on('data', ...) is untyped.

**Comment by poelstra** [comment]
Your use case sounds doable, and I don't understand what this issue is about, sorry.

**Comment by HaKr** [comment]
looks like a request for the counterpart of FileSink, which would provide a stream of lines.

**Comment by MarcWeber** [comment]
I think the batcher transformer satisfies that old need
