### ISSUE TITLE
Read from file?

### ISSUE THREAD

**Issue by AleFons** [poelstra/ts-stream#46]
Is it possible to read from a file? I can render the file as a text or binary format, if necessary.

**Comment by poelstra** [comment]
Sure! There's no built-in `FileSource` though, but you can take a look at the implementation of `FileSink` for inspiration, or with recent NodeJS just do something along the lines of:

```ts
try {
    for (const buffer of myFile) {
        await myStream.write(buffer);
    }
    await mystream.end();
} catch (err) {
   myStream.abort(err);
}
```

Note that this lib is mostly meant for handling object streams, so it will e.g. not try to concatenate buffers.
