### ISSUE TITLE
Question about contributing

### ISSUE THREAD

**Issue by ScottLindley** [poelstra/ts-stream#61]
👋 Hi there. I'm interested in helping out with some of the `TODO` items in the README. I took a look at the [Contributing](https://github.com/poelstra/ts-stream#contributing) section, but it appears I am not permitted to push a branch. If the repo has some protection settings then I'm hoping you could let me know how to proceed.

Thanks for making this cool library!

**Comment by ScottLindley** [comment]
@poelstra

**Comment by poelstra** [comment]
Hey, thanks for your interest! Sorry for the late response, I'm on holiday.

Contributing works like with any other repo on Github: fork this one, push to a branch in that fork (which is yours), and create a pull request. Just Google Pull Request to learn how that all works...

25 jun. 2021 16:26:19 Scott Lindley ***@***.***>:

**Comment by ScottLindley** [comment]
Got it, sorry, I'm used to working in private repositories where forking isn't required. Thanks for the guidance!
