### ISSUE TITLE
Please connect the ended() promises of connected streams

### ISSUE THREAD

**Issue by rogierschouten** [poelstra/ts-stream#7]
It is often handy to know at the reading side whether the end() has completed entirely, i.e. the end() promise has been resolved all the way back to the writer. To this end, it may be possible to connect the ended() method in such a way that it resolves to the ended() of the source.

**Comment by poelstra** [comment]
Basically, this would solve the second concern of https://github.com/poelstra/ts-stream/issues/2#issuecomment-110876701

**Comment by poelstra** [comment]
Fixed in 0.4.1, by using the second argument to `end()`.

This is now already supported by `map()` and `filter()`.

If you want to support it in your own transforms, use it like:
```ts
(readable, writable) => {
    readable.forEach(
        (v) => ...,
        (err) => writable.end(err, readable.ended())
    );
}
```

**Comment by poelstra** [comment]
Btw, it may be a good idea that I rename `ended()` to e.g. `result()` in the near future, as it may be a bit confusing now that the promise returned by `ended()` resolves a lot later than that of `end()`.

**Comment by rogierschouten** [comment]
I don't have a strong opinion, 'result' sounds good too

**Comment by poelstra** [comment]
Renamed to `result()` in 0.5.1.
