### ISSUE TITLE
Consider wrapping error passed to abort() in AbortError

### ISSUE THREAD

**Issue by poelstra** [poelstra/ts-stream#8]
Currently, it's not generically possible to distinguish `abort()`'s from other errors returned by `write()`.

It may be a better idea to make all aborts return e.g. an `AbortError`, which can have the 'original' error for the abort in a `.reason` property, which might even be optional.

In the latter case, its signature could be `abort(error?: Error)`, such that a 'unspecified' abort is also possible.

**Comment by rogierschouten** [comment]
Maybe it would be a good idea then to allow to set the abort error class to use, as applications typically will need their own abort/cancellation error type anyway ;)

**Comment by poelstra** [comment]
Wouldn't the error that you pass to `abort()` be a good fit for such use-cases already?

One of the reasons was that abort could be 'detected' this way in streams further down the line, which could then abort those as well. In that case, the abort error should probably not be made configurable. Although this is maybe no longer needed if we implement the abort-handling as discussed IRL today, and combine that with a third abort-callback to forEach.

Anyway, probably better to handle these other 2 issues first, then think about whether we still need this at all.

**Comment by rogierschouten** [comment]
I think you're right, propose to close this issue.

**Comment by poelstra** [comment]
Seems it's no longer needed (at least for now), closing.
